name: Test and run
on: [push]
jobs:
  c-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Test application
        run: |
          gcc --version
          make test
  c-run:
    runs-on: ubuntu-latest
    needs: c-test
    steps:
      - uses: actions/checkout@v5
      - name: Run application
        run: |
          gcc --version
          make run